### ISSUE TITLE
Крах ej-contests при просмотре clar message

### ISSUE THREAD

**Issue by apathism** [blackav/ejudge#10]
В текущей версии в git можно в форме, в которой задают вопрос не указать, к какой задаче данный вопрос относится.

![screenshot_20161030_175201](https://cloud.githubusercontent.com/assets/364939/19837391/194bd16e-9eca-11e6-99a9-f2b6deaf208a.png)

В таком случае вопрос будет отправлен жюри олимпиады, но при попытке просмотреть его в CGI-программе new-master будет происходить краш ej-contests.

![screenshot_20161030_175722](https://cloud.githubusercontent.com/assets/364939/19837427/599edb94-9eca-11e6-942a-011d341b230a.png)

Судя по всему, CSP-страничка пытается отобразить номер задачи, к которой относится clar, но такой задачи нет и происходит разименование нулевого указателя.

Пример backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007f9786466cea in __strcmp_ssse3 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f9786466cea in __strcmp_ssse3 () from /usr/lib/libc.so.6
#1  0x00007f9783d793be in csp_view_priv_clar_page (ps=0x7f9783f7d138 <page_iface>, log_f=0x2666f90, 
    out_f=0x2669a40, phr=0x7ffeee5da790) at priv_clar_page.c:182
#2  0x0000000000426e8a in priv_external_action (out_f=out_f@entry=0x2669a40, phr=phr@entry=0x7ffeee5da790)
    at new_server_html.c:7062
#3  0x000000000043ae85 in privileged_entry_point (fout=fout@entry=0x2669a40, phr=phr@entry=0x7ffeee5da790)
    at new_server_html.c:7275
#4  0x0000000000441c16 in ns_handle_http_request (state=state@entry=0x1df78f0, p=p@entry=0x233c6d0, 
    fout=fout@entry=0x2669a40, phr=phr@entry=0x7ffeee5da790) at new_server_html.c:11758
#5  0x000000000041859c in cmd_http_request (state=<optimized out>, p=<optimized out>, 
    pkt_size=<optimized out>, pkt_gen=<optimized out>) at new-server.c:397
#6  0x000000000048d1a1 in handle_control_command (p=0x233c6d0, state=0x1df78f0) at server_framework.c:517
#7  nsf_main_loop (state=0x1df78f0) at server_framework.c:644
#8  0x0000000000417b53 in main (argc=<optimized out>, argv=<optimized out>) at new-server.c:838

```

**Comment by blackav** [comment]
исправлено
