### ISSUE TITLE
Сегфолт при попытке использовать конфигурационную переменную задачи для подстановки в конфиг языка

### ISSUE THREAD

**Issue by vvd170501** [blackav/ejudge#142]
### Пример конфига (serve.cfg)
```ini
[language]
...
compiler_env = "EJUDGE_FLAGS=-I ${problem.problem_dir}/include"
```

### Что происходит
ej-contests падает с сегфолтом из-за того, что:

1. Здесь prob == NULL
    https://github.com/blackav/ejudge/blob/5a0d7cc1bb7d3403115d80a9941fe86c4e578e96/lib/varsubst.c#L47

2. Здесь происходит разыменование нулевого указателя `actual_data`
    https://github.com/blackav/ejudge/blob/5a0d7cc1bb7d3403115d80a9941fe86c4e578e96/lib/varsubst.c#L77

### Какой результат хочется видеть

- Возможность подставлять параметры задачи в конфиге языка
- Логирование ошибки и возврат 0, если текущая реализация не позволяет легко добавить подстановку (в какой момент подставляются переменные? язык обязательно должен быть загружен вместе с подстановками до задачи?)

**Comment by blackav** [comment]
У меня и без фикса не падало. А можно трассу стека при падении?

**Comment by vvd170501** [comment]
```c
#0  get_var_value (state=0x556123549230,
    varname=0x556123550e68 "problem_dir",
    global_vars=0x556121cd9720 <section_global_params>,
    problem_vars=0x556121cdbf00 <section_problem_params>,
    language_vars=0x556121cddf20 <section_language_params>,
    tester_vars=0x556121cde520 <section_tester_params>,
    prob=0x0, lang=0x556123554970, tester=0x0)
    at lib/varsubst.c:77
#1  0x0000556121bd3166 in varsubst_heap (state=0x556123549230,
    in_str=0x556123554cf0 "EJ_CLANG_TIDY_COMPILER_FLAGS=-I${problem.problem_dir}/include", free_flag=1,
    global_vars=0x556121cd9720 <section_global_params>,
    problem_vars=0x556121cdbf00 <section_problem_params>,
    language_vars=0x556121cddf20 <section_language_params>,
    tester_vars=0x556121cde520 <section_tester_params>,
    prob=0x0, lang=0x556123554970, tester=0x0)
    at lib/varsubst.c:129
#2  0x0000556121b4d516 in set_defaults (cnts=0x556123546720,
    config_file=0x55612354ba50 "/home/judges/000001/conf/serve.cfg", state=0x556123549230, mode=0, subst_src=0x0, subst_dst=0x0)
    at lib/prepare.c:3576
#3  0x0000556121b55063 in prepare (cnts=0x556123546720,
    state=0x556123549230,
    config_file=0x55612354ba50 "/home/judges/000001/conf/serve.cfg", flags=0, mode=0, opts=0x556121c9dc00 "", managed_flag=1,
    subst_src=0x0, subst_dst=0x0) at lib/prepare.c:5040
#4  0x0000556121bab327 in serve_state_load_contest (
    extra=0x556123549e80, config=0x55612354b0b0, contest_id=1,
    ul_conn=0x55612354baf0, teamdb_callbacks=0x7fff85f5e6e0,
    p_cnts=0x0, no_users_flag=0) at lib/serve_state.c:802
#5  0x0000556121adee31 in privileged_entry_point (
    fout=0x5561235496d0, phr=0x7fff85f61f20)
    at lib/new_server_html.c:9650
#6  0x0000556121b01ade in ns_handle_http_request (
    state=0x55612354c000, fout=0x5561235496d0,
    phr=0x7fff85f61f20) at lib/new_server_html.c:18053
#7  0x0000556121a9e351 in cmd_http_request (
    state=0x55612354c000, p=0x5561235491a0, pkt_size=1371,
    pkt_gen=0x5561235479b0) at bin/ej-contests.c:436
#8  0x0000556121a9f722 in handle_packet_func (
    state=0x55612354c000, p=0x5561235491a0, pkt_size=1371,
    pkt=0x5561235479b0) at bin/ej-contests.c:763
#9  0x0000556121b8dfd5 in handle_control_command (
    state=0x55612354c000, p=0x5561235491a0)
    at lib/server_framework.c:1435
#10 0x0000556121b8ee29 in nsf_main_loop (state=0x55612354c000)
    at lib/server_framework.c:1626
#11 0x0000556121aa06bc in main (argc=5, argv=0x7fff85f62a38)
    at bin/ej-contests.c:1040
```

Только переменная, на которой падает - не `compiler_env`, а `style_checker_env`, но это не должно влиять на результат.

**Comment by blackav** [comment]
дык!
как видно из трассы, подстановка там происходит при загрузке контеста в память, а не при обработке запроса на тестирование.

**Comment by vvd170501** [comment]
Да, проблема была именно при загрузке контеста.
Теперь выдаётся понятная ошибка, спасибо
