### ISSUE TITLE
javac does not work

### ISSUE THREAD

**Issue by blackav** [blackav/ejudge#276]
При компиляции программ на javac и других jvm-языках возникает ошибка:

```
Exception in thread "main" java.lang.InternalError: Error loading java.security file
	at java.base/java.security.Security.initialize(Security.java:126)
	at java.base/java.security.Security$2.run(Security.java:103)
	at java.base/java.security.Security$2.run(Security.java:101)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.base/java.security.Security.<clinit>(Security.java:101)
	at java.base/sun.security.util.SecurityProperties.getOverridableProperty(SecurityProperties.java:57)
	at java.base/sun.security.util.SecurityProperties.privilegedGetOverridable(SecurityProperties.java:48)
	at java.base/sun.security.util.SecurityProperties.includedInExceptions(SecurityProperties.java:72)
	at java.base/sun.security.util.SecurityProperties.<clinit>(SecurityProperties.java:36)
...
```

**Comment by blackav** [comment]
javac ищет файл `java.security` в `/etc/java`. Необходимо монтировать в контейнер `/etc/java` с хост-системы.
